language: android
env:
 - secure: "SWUNVeFUTAZpIH71FbF4IOJIo9+z9UZkRJOJUb69BHFK3HV9V2xRlzQORcsIZDHocU+mjA7+B41qX2WByYw4n7Z+4WmKMN1pMZKSG3Of1+BVDjgvB9xEyIWKK/w4tn+yywmfdOw/rUEYWLnC8uXzM6CqQkthnTMq1XuBenI/onts6Weg10cZlNT4o2vgZl2SFGod17Ho85LUGBwvb5G4BxHFQ0Y3JggGnMX/xHXzwfCoYYM8WJABJu2sXg5htLyIOhp7iLudDOMZUGyZG5MNnKvJqgeHPT9Bl3LC9qbAlheti8HkemEnwKBMo0UZiSR7cDtTNmHC9VjrlwDiVSX6UyIJ20IyHFE8+BoL2gRgyGx57rU07poan5a1nRa9KHhwswTTUO7mymANcQX0naHHZIKY6HJ5XITyQSkQODZ/pZ0vgoNcMQX1a7LTrnT89w2B89LXalr/Tx/A4XQM5MeZ/AUD4akMuZsGxIFpoEOdB3ziKwnO2r+YoY24ReYzbD9ob3Il04OUdvrsk2YpqBhv7oxVT39wZOARZ92hYOT8bRDnpIlFxIJzO+gI0PNbxjBjw9AUtRa0MgMX27M7agZfUA9LUw8WWWUwXoG72LhiavqNp8YqPoBpryqIHny1Mv/ECJddmvfRDG5099D856j7W7gRuVR0MQ3vq6TYyEqAi/o="
 - secure: "GsP3WcQ6m301r6f4Xh5C5gArj+367eWhchkrFE1wDLW4fhDwcekLvB+o3KA5wy/yv7iU+W4OBxlYbEk5CKjJRc9DWPJrIy4+0lILhe18Y+7U4RtTJgUyYKStiC7c7OzalZsTGlxmOSK+tm2QmQPM1iICyap5qeNXvdGinfSL1C8/YdqpGH51fu32ihAUIXcAQElTszX+oRk1Lr4r/1I2zoITZ7ko9PSShMj1lC4xPj8V44Q3b6VxC6mMqKevtMlDBv+1EFq6JI+e6F2zn2cyprOMTJoTOBZdQcBx2hgP4Wv6ft1+OnwACvn8EQuxnutzpD1MuT46tAtbj/84gjBWI80zX/yVjz6LsZBECngX81k/kra6edwPPu4xfKbBMFIxkONmeR+3vHd9TlJPz6rsfLNtvhBhkCs2Wk0a+8si1CkeklteFG+yhtVqt3Lo14ApekyfUBNLLmB2XoWH31vKE5MQrKif16D7uWPyPLWCqffThfsqDD1fPSYEDi9jb0xrZmYRpDBHIiI2MDBuTY2PdLP/PUxJgJZn7yr9YO28niTAlG0H3W4T+jEV2yYTErmhh92ma3I/hvZlLyQ3ewoSon2ve7RG3FhyYGY+euRowcb1KUzC/KWytx28uQso2/4F3cShdUrBOAs8fJnMhm7QSNQGwhxPThSg5hv4LzpwcOs="
 - ARTIFACTS_BUCKET=benboudrastorage

addons:
  artifacts = true
  s3_region = "us-west-2"

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1
    # The SDK version used to compile your project
    - android-23
    - android-22

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck
#after_success:
#  - codecov
